Repository acm-ucr/gamespawn-website, pull requests merged in 2024-05, with the labels that each got.

#87 Created project display component
  src/components/home/ProjDisplay.js
  src/components/home/Project.js
Labels: ready for review

#98 Fix website colors
  src/app/not-found.js
  src/components/Navigation.js
  src/components/events/Card.js
  src/components/home/Landing.js
Labels: bug

#81 Add project pages to navbar
  src/components/Navigation.js
  src/data/NavItems.js
Labels: do not merge, advanced, data

#96 board page: fixed x spacing between profiles + responsibility
  src/components/board/Team.js
Labels: ready for review

#92 Updated Mobile Responsiveness for About Us
  src/components/home/About.js
Labels: ready for review, responsiveness

#102 club cards responsiveness
  src/components/home/ClubCard.js
  src/components/home/ClubCards.js
Labels: responsiveness

#104 Responsify Promote Section
  src/components/home/Promote.js
Labels: ready for review

#108 Landing Mobile Responsiveness
  src/components/home/About.js
  src/components/home/Landing.js
Labels: ready for review, responsiveness

#132 Create Search Component
  src/app/projects/page.js
  src/components/projects/Card.js
  src/components/projects/Cards.js
  src/components/projects/Search.js
  src/data/TempProjects.json
Labels: help wanted, do not merge

#134 Created Card component for projects
  src/components/projects/Card.js
  src/components/projects/Cards.js
  src/components/projects/Search.js
  src/data/TempProjects.js
  src/data/TempProjects.json
Labels: do not merge

#131 Changed footer colors and fixed gradient
  src/app/projects/page.js
  src/components/Footer.js
Labels: bug

#147 modal init
  package-lock.json
  src/components/events/CalendarEvents.js
  src/components/events/Modal.js
Labels: ready for review

#148 Add tags data and filter
  src/components/projects/Cards.js
  src/components/projects/DisplayProjs.js
  src/components/projects/Filters.js
  src/components/projects/Search.js
  src/data/Tags.js
Labels: ready for review, data
